const DEFAULT_SEARCH = 'Paris,fr';

module.exports.DEFAULT_SEARCH = DEFAULT_SEARCH;

module.exports.WEATHER_CONDITTIONS = {
  THUNDERSTORM: 'THUNDERSTORM', // @TODO
  DRIZZLE: 'DRIZZLE', // @TODO
  RAIN: 'RAIN', // @TODO
  SNOW: 'SNOW', // @TODO
  CLOUDS: 'CLOUDS', // @TODO
  CLEAR: 'CLEAR', // @TODO
};
