/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'color.chroma.000': 0.05,
  'color.chroma.100': 0.1,
  'color.chroma.200': 0.2,
  'color.chroma.300': 0.3,
  'color.chroma.400': 0.25,
  'color.chroma.500': 0.15,
  'color.chroma.600': 0.1,
  'color.chroma.neutral': 0,
  'color.hue.framboise': 263.8,
  'color.hue.gray': 0,
  'color.hue.gray-violet': 308.5,
  'color.hue.neonblue': 273.95,
  'color.hue.seagreen': 215.77,
  'color.hue.teal': 184.22,
  'color.hue.vintagerose': 11.66,
  'color.hue.violet': 285.94,
  'color.hue.yellow': 263.84,
  'color.lightness.000': 98,
  'color.lightness.100': 88,
  'color.lightness.200': 76,
  'color.lightness.300': 65,
  'color.lightness.400': 54,
  'color.lightness.500': 42,
  'color.lightness.600': 32,
  'color.lightness.dark': 23.5,
  'color.lightness.light': 100,
  'color.theme.accent': 215.77,
  'color.theme.highlight': 11.66,
  'color.theme.neutral': 0,
  'color.theme.primary': 285.94,
  'color.theme.surface': 308.5,
  'font.sansSerif': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Noto Sans', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
  'size.base': '1rem',
  'size.large': '12px',
  'size.medium': '8px',
  'size.small': '6px',
  'size.xlarge': '16px',
  'size.xsmall': '4px',
};

export const meta = {
  'color.chroma.000': {
    _original: {
      $value: 0.05,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.000',
    $type: 'number',
    $value: 0.05,
  },
  'color.chroma.100': {
    _original: {
      $value: 0.1,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.100',
    $type: 'number',
    $value: 0.1,
  },
  'color.chroma.200': {
    _original: {
      $value: 0.2,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.200',
    $type: 'number',
    $value: 0.2,
  },
  'color.chroma.300': {
    _original: {
      $value: 0.3,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.300',
    $type: 'number',
    $value: 0.3,
  },
  'color.chroma.400': {
    _original: {
      $value: 0.25,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.400',
    $type: 'number',
    $value: 0.25,
  },
  'color.chroma.500': {
    _original: {
      $value: 0.15,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.500',
    $type: 'number',
    $value: 0.15,
  },
  'color.chroma.600': {
    _original: {
      $value: 0.1,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.600',
    $type: 'number',
    $value: 0.1,
  },
  'color.chroma.neutral': {
    _original: {
      $value: 0,
    },
    _group: {
      id: 'color.chroma',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.chroma.neutral',
    $type: 'number',
    $value: 0,
  },
  'color.hue.framboise': {
    _original: {
      $value: 263.8,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.framboise',
    $type: 'number',
    $value: 263.8,
  },
  'color.hue.gray': {
    _original: {
      $value: 0,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.gray',
    $type: 'number',
    $value: 0,
  },
  'color.hue.gray-violet': {
    _original: {
      $value: 308.5,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.gray-violet',
    $type: 'number',
    $value: 308.5,
  },
  'color.hue.neonblue': {
    _original: {
      $value: 273.95,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.neonblue',
    $type: 'number',
    $value: 273.95,
  },
  'color.hue.seagreen': {
    _original: {
      $value: 215.77,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.seagreen',
    $type: 'number',
    $value: 215.77,
  },
  'color.hue.teal': {
    _original: {
      $value: 184.22,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.teal',
    $type: 'number',
    $value: 184.22,
  },
  'color.hue.vintagerose': {
    _original: {
      $value: 11.66,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.vintagerose',
    $type: 'number',
    $value: 11.66,
  },
  'color.hue.violet': {
    _original: {
      $value: 285.94,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.violet',
    $type: 'number',
    $value: 285.94,
  },
  'color.hue.yellow': {
    _original: {
      $value: 263.84,
    },
    _group: {
      id: 'color.hue',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.hue.yellow',
    $type: 'number',
    $value: 263.84,
  },
  'color.lightness.000': {
    _original: {
      $value: 98,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.000',
    $type: 'percentage',
    $value: 98,
    value: 98,
  },
  'color.lightness.100': {
    _original: {
      $value: 88,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.100',
    $type: 'percentage',
    $value: 88,
    value: 88,
  },
  'color.lightness.200': {
    _original: {
      $value: 76,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.200',
    $type: 'percentage',
    $value: 76,
    value: 76,
  },
  'color.lightness.300': {
    _original: {
      $value: 65,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.300',
    $type: 'percentage',
    $value: 65,
    value: 65,
  },
  'color.lightness.400': {
    _original: {
      $value: 54,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.400',
    $type: 'percentage',
    $value: 54,
    value: 54,
  },
  'color.lightness.500': {
    _original: {
      $value: 42,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.500',
    $type: 'percentage',
    $value: 42,
    value: 42,
  },
  'color.lightness.600': {
    _original: {
      $value: 32,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.600',
    $type: 'percentage',
    $value: 32,
    value: 32,
  },
  'color.lightness.dark': {
    _original: {
      $value: 23.5,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.dark',
    $type: 'percentage',
    $value: 23.5,
    value: 23.5,
  },
  'color.lightness.light': {
    _original: {
      $value: 100,
    },
    _group: {
      id: 'color.lightness',
      $extensions: {
        requiredModes: [],
      },
      $type: 'percentage',
    },
    id: 'color.lightness.light',
    $type: 'percentage',
    $value: 100,
    value: 100,
  },
  'color.theme.accent': {
    _original: {
      $value: '{color.hue.seagreen}',
    },
    _group: {
      id: 'color.theme',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.theme.accent',
    $type: 'number',
    $value: 215.77,
  },
  'color.theme.highlight': {
    _original: {
      $value: '{color.hue.vintagerose}',
    },
    _group: {
      id: 'color.theme',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.theme.highlight',
    $type: 'number',
    $value: 11.66,
  },
  'color.theme.neutral': {
    _original: {
      $value: '{color.hue.gray}',
    },
    _group: {
      id: 'color.theme',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.theme.neutral',
    $type: 'number',
    $value: 0,
  },
  'color.theme.primary': {
    _original: {
      $value: '{color.hue.violet}',
    },
    _group: {
      id: 'color.theme',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.theme.primary',
    $type: 'number',
    $value: 285.94,
  },
  'color.theme.surface': {
    _original: {
      $value: '{color.hue.gray-violet}',
    },
    _group: {
      id: 'color.theme',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'color.theme.surface',
    $type: 'number',
    $value: 308.5,
  },
  'font.sansSerif': {
    _original: {
      $value: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Noto Sans', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
    },
    _group: {
      id: 'font',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'font.sansSerif',
    $type: 'fontFamily',
    $value: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Noto Sans', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
  },
  'size.base': {
    _original: {
      $value: '1rem',
    },
    _group: {
      id: 'size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'size.base',
    $type: 'dimension',
    $value: '1rem',
  },
  'size.large': {
    _original: {
      $value: '12px',
    },
    _group: {
      id: 'size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'size.large',
    $type: 'dimension',
    $value: '12px',
  },
  'size.medium': {
    _original: {
      $value: '8px',
    },
    _group: {
      id: 'size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'size.medium',
    $type: 'dimension',
    $value: '8px',
  },
  'size.small': {
    _original: {
      $value: '6px',
    },
    _group: {
      id: 'size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'size.small',
    $type: 'dimension',
    $value: '6px',
  },
  'size.xlarge': {
    _original: {
      $value: '16px',
    },
    _group: {
      id: 'size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'size.xlarge',
    $type: 'dimension',
    $value: '16px',
  },
  'size.xsmall': {
    _original: {
      $value: '4px',
    },
    _group: {
      id: 'size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'size.xsmall',
    $type: 'dimension',
    $value: '4px',
  },
};

export const modes = {};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
