<script lang="ts">
	import type {FormProps, TestForm} from '#types'
	import {onMount} from 'svelte'
	import {enhance} from '$app/forms'

	import {TestFormValidator} from '#lib/utils/validate.js'
	import Button from '#lib/components/blocks/buttons/Button.svelte'
	import Feedback from '#lib/components/blocks/global/Feedback.svelte'
	import Input from '#lib/components/blocks/inputs/Input.svelte'
	import InputCheck from '#lib/components/blocks/inputs/InputCheck.svelte'
	import InputRadio from '#lib/components/blocks/inputs/InputRadio.svelte'
	import InputGroup from '#lib/components/blocks/inputs/InputGroup.svelte'
	import InputPassword from '#lib/components/blocks/inputs/InputPassword.svelte'
	import FormValidator from '#lib/utils/browser/FormValidator.svelte'

	import TestContext from '#tests/browser/TestContext.svelte'

	let {
		id = 'test-form',
		title = 'Test Form',
		description = 'A sample form for testing validation functionality.',
		actionPath, // 'ui'
		formaction, // 'signup'
		redirect,
		container,
		depth = 2, // <h*> element depth
		size,
		color = 'primary',
		variant = 'fill',
		asset = 'log',
		align = 'center',
		background,
	}: FormProps = $props()

	let boundForm: HTMLFormElement | undefined = $state()
	let formData: FormData | undefined = $state()
	let validator: FormValidator<TestForm> = new FormValidator(TestFormValidator)
	let disabled: boolean | undefined = $derived(undefined)

	$effect(() => {
		disabled = validator.formHasErrors() ? true : undefined
	})

	let successPlaceholder: boolean = $state(false)

	// TODO: Generate this mapping from the schema definition
	const inputTypes: {[name: string]: string} = {
		name: 'text',
		phone: 'phone',
		email: 'email',
		password: 'password',
		confirm_password: 'password',
		postcode: 'postcode',
		// description: 'textarea',
		checkbox: 'checkbox',
		// select: 'select',
		disabled_field: 'disabled_field',
		radio_group: 'radio_group',
		checkbox_group: 'checkbox_group',
	}

	/**
	 * For the form to work:
	 * - `formaction` and `redirect` must be defined (`action` must be defined)
	 * - The `<form>` element must set `action` to `?/${action}` instead of `undefined` (see `action` prop in form element)
	 */
	let action = $derived(
		formaction && redirect ? `${formaction}&redirectTo=${redirect}` : undefined,
	)

	function handleSubmit(event: Event) {
		event.preventDefault()

		// Submit the form here
		// ...
		if (!validator.errors.length) {
			successPlaceholder = true
		}
	}

	function handleFocus(event: Event) {
		validator.touchInput(event)
	}

	function handleBlur(event: Event) {
		validator.validateInput(event)
	}

	function handleInput(event: Event) {
		validator.changeInput(event)
		validator.validateInput(event)
	}

	onMount(() => {
		if (boundForm) {
			formData = new FormData(boundForm)
			//  Default function generated by the `@fat-fuzzy/validation` package for demo
			validator.init(formData, inputTypes)
			return () => {
				validator.destroy()
			}
		}
	})
</script>

<TestContext>
	<div class={`ravioli:${size} ${background} l:${container}:${size}`}>
		{#if successPlaceholder}
			<Feedback status="success" context="form">Form submitted!</Feedback>
		{:else}
			<form
				{id}
				method="POST"
				class={`l:stack:${size} ravioli:${size}`}
				action={action && actionPath ? `${actionPath}?/${action}` : undefined}
				use:enhance
				bind:this={boundForm}
				onsubmit={handleSubmit}
			>
				{#if validator}
					<header class={`l:stack:${size} text:${align} ${asset}`}>
						<svelte:element this={`h${depth}`}>{title}</svelte:element>
						<p class={`font:${size}`}>{description}</p>
					</header>
					<Input
						id="name"
						type="text"
						name="name"
						label="Username"
						required
						{size}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('name')}
						autocomplete="username"
					/>
					<Input
						id="phone"
						type="phone"
						name="phone"
						label="Phone"
						required
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('phone')}
					/>
					<Input
						id="email"
						type="email"
						name="email"
						label="Email"
						required
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('email')}
					/>
					<Input
						id="postcode"
						type="text"
						name="postcode"
						label="Postcode"
						required
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('postcode')}
					/>
					<!-- Input
					id="description"
					type="description"
					name="description"
					label="Description"
					required
					{size}
					{color}
					{variant}
					onfocus={handleFocus}
					onblur={handleBlur}
					oninput={handleInput}
					errors={validator.getFieldErrors('description')}
				/ -->
					<InputCheck
						id="checkbox"
						name="checkbox"
						label="Checkbox"
						required
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						checked={false}
						errors={validator.getFieldErrors('checkbox')}
					/>
					<!-- Input
					id="select"
					type="select"
					name="select"
					label="Select"
					required
					{size}
					{color}
					{variant}
					onfocus={handleFocus}
					onblur={handleBlur}
					oninput={handleInput}
					errors={validator.getFieldErrors('select')}
				/ -->
					<Input
						id="disabled_field"
						type="text"
						name="disabled_field"
						label="Disabled Field"
						value="Disabled Value"
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						disabled
						errors={validator.getFieldErrors('disabled_text')}
					/>
					<InputGroup
						context="form"
						id="checkbox_group"
						type="check"
						name="checkbox_group"
						legend="Checkbox Group"
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('checkbox_group')}
						justify="between"
					>
						<InputCheck
							id="unique_choice_1"
							name="choice_1"
							label="Checkbox 1"
							{size}
							{color}
							{variant}
							justify="between"
							onfocus={handleFocus}
							onblur={handleBlur}
							oninput={handleInput}
							errors={validator.getFieldErrors('choice_1')}
						/>
						<br />
						<InputCheck
							id="choice_2"
							name="choice_2"
							label="Checkbox 2"
							{size}
							{color}
							{variant}
							justify="between"
							onfocus={handleFocus}
							onblur={handleBlur}
							oninput={handleInput}
							errors={validator.getFieldErrors('choice_2')}
						/>
					</InputGroup>
					<InputGroup
						context="form"
						id="radio_group"
						type="radio"
						name="radio_group"
						legend="Radio Group"
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('radio_group')}
						justify="between"
					>
						<InputRadio
							id="unique_choice_1"
							name="unique_choice_1"
							label="Radio 1"
							{size}
							{color}
							{variant}
							justify="between"
							onfocus={handleFocus}
							onblur={handleBlur}
							oninput={handleInput}
							errors={validator.getFieldErrors('unique_choice_1')}
						/>
						<br />
						<InputRadio
							id="unique_choice_2"
							name="unique_choice_2"
							label="Radio 2"
							{size}
							{color}
							{variant}
							justify="between"
							onfocus={handleFocus}
							onblur={handleBlur}
							oninput={handleInput}
							errors={validator.getFieldErrors('unique_choice_2')}
						/>
					</InputGroup>
					<InputPassword
						type="password"
						id="password"
						name="password"
						label="Password"
						required
						{size}
						{color}
						{variant}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('password')}
						autocomplete="new-password"
					/>
					<InputPassword
						id="confirm_password"
						type="password"
						name="confirm_password"
						label="Confirm Pwd"
						required
						{size}
						{color}
						{variant}
						disabled={validator.getFieldErrors('password').length
							? true
							: undefined}
						onfocus={handleFocus}
						onblur={handleBlur}
						oninput={handleInput}
						errors={validator.getFieldErrors('confirm_password')}
						autocomplete="new-password"
					/>
					<Button
						id="button-submit-signup"
						{size}
						{color}
						{variant}
						name="submit"
						{disabled}
					>
						Submit
					</Button>
				{/if}
			</form>
		{/if}
	</div>
</TestContext>
