import type {NavItem} from '$types'

export const links = [
	{slug: 'about', label: 'About', layout: 'sidebar'},
	{slug: 'ui', label: 'UI', layout: 'sidebar'},
	{slug: 'blog', label: 'Blog', layout: 'sidebar'},
	{slug: 'play', label: 'Play', layout: 'sidebar'},
]

export const linksSocials = [
	{
		id: 'link-github',
		label: 'GitHub',
		url: 'https://github.com/fat-fuzzy/rocks',
		asset: 'github',
		assetType: 'svg',
		shape: 'round',
		size: 'sm',
		color: 'primary',
	},
	{
		id: 'link-rss',
		label: 'RSS',
		url: 'https://rocks.pages.dev/blog/rss.xml',
		asset: 'rss',
		assetType: 'svg',
		shape: 'square',
		size: 'sm',
		color: 'primary',
	},
]

export const pages: {[key: string]: NavItem} = {
	blog: {
		slug: 'blog',
		label: 'Blog',
		title: 'Content',
		asset: 'pencil',
		assetType: 'emoji',
		layout: 'metro',
		items: [],
		actionPath: '/blog',
	},
	about: {
		slug: 'about',
		label: 'About',
		title: 'Doc',
		asset: 'doc',
		assetType: 'emoji',
		layout: 'voyager',
		actionPath: '/about',
		items: [
			{
				slug: 'usage',
				title: 'Usage',
				label: 'Usage',
				asset: 'usage',
				assetType: 'emoji',
				actionPath: '/about/usage',
				items: [],
			},
			{
				slug: 'decisions',
				title: 'Decisions',
				label: 'Decisions',
				asset: 'decisions',
				assetType: 'emoji',
				actionPath: '/about/decisions',
				items: [],
			},
			{
				slug: 'speaking',
				title: 'Speaking',
				label: 'Speaking',
				asset: 'speaking',
				assetType: 'emoji',
				layout: 'metro',
				actionPath: '/about/speaking',
				items: [],
			},
		],
	},
	play: {
		slug: 'play',
		label: 'Play',
		title: 'Sketches',
		asset: 'rainbow',
		assetType: 'emoji',
		layout: 'metro',
		actionPath: '/play',
		items: [
			{
				slug: 'projects',
				title: 'Projects',
				label: 'Projects',
				asset: 'projects',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/play/projects',
				items: [],
			},
			{
				slug: 'learning',
				title: 'Learning',
				label: 'Learning',
				asset: 'learning',
				layout: 'tram',
				actionPath: '/play/learning',
				items: [],
			},
		],
	},
	ui: {
		slug: 'ui', // root path of the Playbook
		title: 'UI Library',
		asset: 'playbook',
		assetType: 'emoji',
		label: 'UI',
		layout: 'voyager',
		actionPath: '/ui',
		items: [
			{
				slug: 'tokens',
				title: 'Tokens',
				label: 'Tokens',
				asset: 'tokens',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/tokens',
				items: [],
			},
			{
				slug: 'blocks',
				title: 'Blocks',
				label: 'Blocks',
				asset: 'blocks',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/blocks',
				items: [],
			},
			{
				slug: 'layouts',
				title: 'Layouts',
				label: 'Layouts',
				asset: 'layouts',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/layouts',
				items: [],
			},
			{
				slug: 'recipes',
				title: 'Recipes',
				label: 'Recipes',
				asset: 'recipes',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/recipes',
				items: [],
			},
			{
				slug: 'raw',
				title: 'Raw',
				label: 'Raw',
				asset: 'raw',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/raw',
				items: [],
			},
		],
	},
	media: {
		slug: 'media',
		label: 'Media',
		title: 'Collections',
		asset: 'pencil',
		assetType: 'emoji',
		layout: 'sidebar',
		items: [],
	},
}
