<script lang="ts">
	import type {SignUpProps} from '$types'
	import {onMount} from 'svelte'
	import {enhance} from '$app/forms'
	import Button from '$lib/components/blocks/buttons/Button.svelte'
	import Feedback from '$lib/components/blocks/global/Feedback.svelte'
	import Input from '$lib/components/blocks/inputs/Input.svelte'
	import InputPassword from '$lib/components/blocks/inputs/InputPassword.svelte'
	import FormValidator from '$lib/utils/dom/FormValidator.svelte'

	let {
		id = 'sign-up-form',
		title = 'Sign Up',
		description = 'A sample signup form',
		actionPath, // 'ui'
		formaction, // 'signup'
		redirect,
		container,
		level = 2, // <h*> element level
		size,
		color = 'primary',
		variant = 'fill',
		asset = 'log',
		align = 'center',
		background = 'contrast',
	}: SignUpProps = $props()

	let boundForm: HTMLFormElement | undefined = $state()
	let formData: FormData | undefined = $state()
	let validator: FormValidator = new FormValidator('SignUpValidationFunction')
	let disabled: boolean | undefined = $derived(
		validator.formHasErrors() ? true : undefined,
	)
	let successPlaceholder: boolean = $state(false)

	// TODO: Integrate inputTypes into validator from schema
	const inputTypes: {[name: string]: string} = {
		sample_username: 'text',
		sample_email: 'email',
		sample_password: 'password',
		confirm_password: 'password',
	}

	/**
	 * For the form to work:
	 * - `formaction` and `redirect` must be defined (`action` must be defined)
	 * - The `<form>` element must set `action` to `?/${action}` instead of `undefined` (see `action` prop in form element)
	 */
	let action = $derived(
		formaction && redirect ? `${formaction}&redirectTo=${redirect}` : undefined,
	)

	function handleSubmit(event: Event) {
		event.preventDefault()

		// Submit the form here
		// ...
		if (!validator.errors.length) {
			successPlaceholder = true
		}
	}

	function handleFocus(event: Event) {
		validator.touchInput(event)
	}

	function handleBlur(event: Event) {
		validator.validateInput(event)
	}

	function handleInput(event: Event) {
		validator.changeInput(event)
		validator.validateInput(event)
	}

	onMount(() => {
		if (boundForm) {
			formData = new FormData(boundForm)
			//  Default function generated by the `@fat-fuzzy/validation` package for demo
			validator.init(formData, inputTypes)
			return () => {
				validator.destroy()
			}
		}
	})
</script>

<div class={`ravioli:${size} ${background} l:${container}:${size}`}>
	{#if successPlaceholder}
		<Feedback status="success" context="form">Form submitted!</Feedback>
	{:else}
		<form
			{id}
			method="POST"
			class={`l:stack:${size} ravioli:${size}`}
			action={action && actionPath ? `${actionPath}?/${action}` : undefined}
			use:enhance
			bind:this={boundForm}
			onsubmit={handleSubmit}
		>
			{#key validator}
				<header class={`l:stack:${size} text:${align} ${asset}`}>
					<svelte:element this={`h${level}`}>{title}</svelte:element>
					<p class={`font:${size}`}>{description}</p>
				</header>
				<Input
					id="username"
					type="text"
					name="sample_username"
					label="Username"
					required
					{size}
					{variant}
					onfocus={handleFocus}
					onblur={handleBlur}
					oninput={handleInput}
					{validator}
					autocomplete="username"
				/>
				<Input
					id="email"
					type="email"
					name="sample_email"
					label="Email"
					required
					{size}
					{color}
					{variant}
					onfocus={handleFocus}
					onblur={handleBlur}
					oninput={handleInput}
					{validator}
				/>
				<InputPassword
					type="password"
					id="password"
					name="sample_password"
					label="Password"
					required
					{size}
					{color}
					{variant}
					onfocus={handleFocus}
					onblur={handleBlur}
					oninput={handleInput}
					{validator}
					autocomplete="new-password"
				/>
				<InputPassword
					id="confirm_password"
					type="password"
					name="confirm_password"
					label="Confirm Password"
					required
					{size}
					{color}
					{variant}
					disabled={validator.getFieldErrors('sample_password')
						? true
						: undefined}
					onfocus={handleFocus}
					onblur={handleBlur}
					oninput={handleInput}
					{validator}
					autocomplete="new-password"
				/>
				<Button
					id="button-submit-signup"
					{size}
					{color}
					{variant}
					name="submit"
					{disabled}
				>
					Submit
				</Button>
			{/key}
		</form>
	{/if}
</div>
