import type {NavItem, UiAssetType} from '$types'

const links = [
	{slug: 'style', label: 'Style', layout: 'sidebar'},
	{slug: 'tests', label: 'Tests', layout: 'tgv'},
	// {slug: 'ui', label: 'UI', layout: 'sidebar'},
]

const linksSocials = [
	{
		id: 'link-github',
		label: 'UI Package - GitHub',
		url: 'https://github.com/fat-fuzzy/rocks/tree/main/packages/ui',
		asset: 'github',
		assetType: 'svg' as UiAssetType,
		shape: 'round',
		size: 'sm',
		color: 'primary',
	},
	{
		id: 'link-github',
		label: 'Style Package - GitHub',
		url: 'https://github.com/fat-fuzzy/rocks/tree/main/packages/style',
		asset: 'github',
		assetType: 'svg' as UiAssetType,
		shape: 'round',
		size: 'sm',
		color: 'primary',
	},
	{
		id: 'link-doc',
		label: 'Style Doc',
		url: 'https://rocks.pages.dev/about/usage/style',
		asset: 'doc',
		assetType: 'svg' as UiAssetType,
		shape: 'square',
		size: 'sm',
		color: 'primary',
	},
	{
		id: 'link-doc',
		label: 'UI Doc',
		url: 'https://rocks.pages.dev/ui',
		asset: 'doc',
		assetType: 'svg' as UiAssetType,
		shape: 'square',
		size: 'sm',
		color: 'primary',
	},
]

export const pages: {[key: string]: NavItem} = {
	tests: {
		slug: 'tests',
		label: 'Tests',
		title: 'e2e',
		asset: 'test',
		assetType: 'emoji',
		layout: 'tgv',
		items: [
			{
				slug: 'forms',
				title: 'Forms',
				label: 'Forms',
				asset: 'forms',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/tests/forms',
				items: [],
			},
			{
				slug: 'recipes',
				title: 'Recipes',
				label: 'Recipes',
				asset: 'recipes',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/tests/recipes',
				items: [],
			},
		],
		actionPath: '/tests',
	},
	style: {
		slug: 'style',
		label: 'Style',
		title: 'style',
		asset: 'rainbow',
		assetType: 'emoji',
		layout: 'tgv',
		items: [],
		actionPath: '/style',
	},
	ui: {
		slug: 'ui', // root path of the Playbook
		title: 'UI Drafts',
		asset: 'playbook',
		assetType: 'emoji',
		label: 'UI',
		layout: 'voyager',
		actionPath: '/ui',
		items: [
			{
				slug: 'tokens',
				title: 'Tokens',
				label: 'Tokens',
				asset: 'tokens',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/tokens',
				items: [],
			},
			{
				slug: 'blocks',
				title: 'Blocks',
				label: 'Blocks',
				asset: 'blocks',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/blocks',
				items: [],
			},
			{
				slug: 'layouts',
				title: 'Layouts',
				label: 'Layouts',
				asset: 'layouts',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/layouts',
				items: [],
			},
			{
				slug: 'recipes',
				title: 'Recipes',
				label: 'Recipes',
				asset: 'recipes',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/recipes',
				items: [],
			},
			{
				slug: 'raw',
				title: 'Raw',
				label: 'Raw',
				asset: 'raw',
				assetType: 'emoji',
				layout: 'tram',
				actionPath: '/ui/raw',
				items: [],
			},
		],
	},
}

export default {links, linksSocials, pages}
