name: Integrity Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-integrity-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd packages/validation  # Change to your specific package directory
          npm install

      - name: Run integrity tests
        run: |
          cd packages/validation  # Test integrity of AJV validation functions
          npm run test:integrity
